### ISSUE TITLE
Relatively slow performance

### ISSUE THREAD

**Issue by wycats** [evanphx/kpeg#22]
I have written a JavaScript parser (wycats/parsejs) using kpeg, and get between 15k and 30k bytes per second when parsing JavaScript files. This seems slow and it would be nice to be figure out a way to improve performance.

There is a good sample file in the fixtures in the ParseJS at https://github.com/wycats/parsejs/blob/master/spec/fixtures/sizzle.js

Here's a simple benchmark:

```ruby
require "benchmark"
require "parsejs"

parser = ParseJS::Parser.new(File.read("sizzle.js"))

Benchmark.bm do |x|
  x.report("sizzle") { parser.parse }
end
```

Here is the output I get:

```
~/Code/parsejs ‹ruby-1.8.7›  ‹master*› $ rvm 1.8.7
~/Code/parsejs ‹ruby-1.8.7›  ‹master*› $ ruby -rubygems benchmark.rb
      user     system      total        real
sizzle  3.790000   0.060000   3.850000 (  3.840110)
~/Code/parsejs ‹ruby-1.8.7›  ‹master*› $ rvm 1.9.3
~/Code/parsejs ‹ruby-1.9.3›  ‹master*› $ ruby -rubygems benchmark.rb
       user     system      total        real
sizzle  1.380000   0.020000   1.400000 (  1.408474)
```

**Comment by evanphx** [comment]
It's still not as fast as it could be. PEGs aren't usually super fast, but it could be profiled.
