### ISSUE TITLE
\r is not escaped in kpeg output

### ISSUE THREAD

**Issue by drbrain** [evanphx/kpeg#25]
Instead of `"\r"`, a raw carriage return is placed in the output.

See http://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/lib/rdoc/markdown.rb?r1=38102&r2=38101&pathrev=38102 

Source grammar is here:

https://github.com/rdoc/rdoc/blob/master/lib/rdoc/markdown.kpeg

**Comment by evanphx** [comment]
Eric fixed this back in a88bcbca.
