### ISSUE TITLE
a question (or feature request)

### ISSUE THREAD

**Issue by artbot1** [evanphx/kpeg#28]
hi,

is there a possibility to count the number of repetitions:

space1= " "
space2= "[SPACE]"
spacese= < (space1 | space2)+ > {how to get the number spaces? text.size won't work for this}

mayby someting like rule.number_of_repetitions could be included (or does already exist???)

spacese= < (space1 | space2)+ > { rule.number_of_repetitions}

thanx

artur

**Comment by evanphx** [comment]
Why won't `text.size` work?

**Comment by artbot1** [comment]
text.size of " [SPACE][SPACE]" would give 15, but rule.number_of_repetitions should give 3

using text.gsub("[SPACE]"," ").size is one possibility, but i think rule.number_of_repetitions is
more elegant (and efficient ...)

**Comment by evanphx** [comment]
Ah, I see. There is not a builtin repetition count, but you can create one. I think this would work:

`spaces = < { space_count = } ((space1 | space2) { space_count += 1})+ > { space_count }`
