### ISSUE TITLE
Labeled capture groups aren't working

### ISSUE THREAD

**Issue by marnen** [evanphx/kpeg#36]
I think I found a bug in KPeg 1.1.0 (Ruby 2.3.1p112 on Ubuntu).

I have the following lines in a grammar:
```
DIGIT = /[0-9]/
digits = DIGIT+
integer = < negative_sign? digits:num > { puts "num: #{num}, text: #{text}"}
```
When the `integer` pattern is matched, the block is called as expected, but the output is 
```
num: , text: 575
```
Breaking into the block with the debugger reveals that, although `num` exists as a local variable (it's in `binding.local_variables`, for example), it is always nil even when the `digits` pattern matches. Help?

**Comment by evanphx** [comment]
You didn't define a block for digit so the rules return value is nil. You need to add a block to it to get a value from it.

**Comment by marnen** [comment]
@evanphx Thanks; that wasn't entirely clear from the docs. I'll try that!
