### ISSUE TITLE
no git tags for released version

### ISSUE THREAD

**Issue by Segaja** [evanphx/kpeg#50]
Hi, https://rubygems.org/gems/kpeg lists version `1.3.1` as the latest, but https://github.com/evanphx/kpeg/tags only lists `1.1.0` as the latest version.

I'm trying to package this library for Arch Linux and we use the git repository tags/releases as source for our packages, so these tags would be really appreciated.

**Comment by evanphx** [comment]
The tags for v1.3.x should be there now.
